#!/usr/bin/zsh

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
sshfile="$SCRIPTPATH/.LinJMP"

source $sshfile

if [ $2 ]
then
  ssh -t $sshuser@${linjmpbox[$1]} "ssh -o ServerAliveInterval=60 $2"
else
  ssh -t $sshuser@${linjmpbox[$1]}
fi
